## name: rabbit
## author: ADHD-exe

#: The basic colors

 background #010212
 foreground #8688ff
selection_foreground  #E19FB8
selection_background  #465688

background_opacity 0.9
background_blur 20
dynamic_background_opacity yes
background_image none
background_image_layout tiled
background_image_linear no
background_tint 0.0
background_tint_gaps 1.0
transparent_background_colors  #8688ff
dim_opacity 0.4

#: cursor colors
 cursor #00ffd4
 cursor_text_color #000b09
 cursor_trail_color #00ffd4

#: URL underline color when hovering with mouse
 url_color #ccff92
 url_color #8930FF

#: kitty window border colors and terminal bell colors
visual_bell_color     


#: Tab bar colors
 active_tab_foreground #050816
 active_tab_background #9411ff
 inactive_tab_foreground #5555ff
 inactive_tab_background #192555
 tab_bar_background none


 scrollbar_handle_color foreground
 scrollbar_track_color foreground

 tab_bar_margin_color none

mark1_foreground #050816
mark1_background #00ffd4
mark2_foreground #050816
mark2_background #8c6bff
mark3_foreground #050816
mark3_background #ff3bd4
active_border_color #22e6ff
inactive_border_color #3a2c7a
bell_border_color #4d06ff
#: The basic 16 colors
 Black / Gray
color0  #06090d
color8  #0a0a1f

# Red / Pink neon
color1  #ff00c8
color9  #eb50ff

# Green / Aqua
color2  #00ffd4
color10 #69ffee

# Yellow
color3  #ffe066
color11 #feffcb

# Blue
color4  #004cff
color12 #4343ff

# Purple
color5  #7700ff
color13 #805aff

# Cyan / Sky
color6  #00aaff
color14 #4c94ff

# Foreground lavender family
color7  #8688ff
color15 #97a7ff
 
